# Generated by Django 5.1.6 on 2025-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_lifestyletest_lipidprofiletest_symptomstest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestyletest',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lifestyletest',
            name='obesity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='alcohol_consumption',
            field=models.CharField(choices=[('occasionally', 'Occasionally'), ('regularly', 'Regularly'), ('never', 'Never')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='exercise_regularity',
            field=models.CharField(choices=[('everyday', 'Everyday'), ('occasionally', 'Occasionally'), ('never', 'Never')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='feeling_useless',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly Agree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='health_conditions',
            field=models.CharField(choices=[('normal', 'Normal'), ('hypertension', 'Hypertension'), ('diabetes', 'Diabetes'), ('asthma', 'Asthma'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='lifestyle',
            field=models.CharField(choices=[('lying_around', 'Lying Around'), ('active', 'Active Lifestyle'), ('balanced', 'Balanced Lifestyle'), ('social', 'Very Social'), ('busy', 'Busy Lifestyle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='location',
            field=models.CharField(choices=[('north_india', 'North India'), ('south_india', 'South India'), ('east_india', 'East India'), ('west_india', 'West India'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='not_good_enough',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly Agree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='positive_attitude',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly Agree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='proud_of',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly Agree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='self_respect',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly Agree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='self_satisfaction',
            field=models.CharField(choices=[('strongly_disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neutral'), ('agree', 'Agree'), ('strongly_agree', 'Strongly Agree')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lifestyletest',
            name='sleeping_hours',
            field=models.CharField(choices=[('less_than_5', 'Less than 5 hours'), ('5_to_7', '5 to 7 hours'), ('more_than_7', 'More than 7 hours')], max_length=20),
        ),
    ]
