# Generated by Django 5.1.6 on 2025-02-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_lifestyletest_bmi_lifestyletest_obesity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomstest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
