# Generated by Django 5.1.6 on 2025-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_uploadeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='document',
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='uploaded_documents/'),
        ),
    ]
